version: 2
updates:
  - package-ecosystem: "terraform"
    directories: "/modules/*/"
    schedule:
      interval: "daily"
    assignees:
      - acch
    reviewers:
      - acch
    open-pull-requests-limit: 10
